package com.module.purchase.enums;

public enum EntityType {
    
    EMPLOYEE,
    DEPARTMENT,
    ROLE,
    ITEM,
    VENDOR,
    CATEGORY,
    PURCHASE_REQUEST,
    PURCHASE_ORDER,
    USER,
    ASSIGNING_CONFIG,
    ASSIGNING_APPROVAL,
    DEPARTMENT_BUDGET,
    AUDIT_LOGS,
    VIEW_PERMISSION,
    UNIT,
    ITEM_VARIANT,
    REPEATED_PERIOD,
    REQUEST_FOR_QUOTATION
}
