package com.module.purchase.enums;

public enum EntityType {
    
    ASSIGNING_CONFIG,
    ASSIGNING_APPROVAL,
    USER,
    ROLE,
    EMPLOYEE,
    DEPARTMENT,
    DEPARTMENT_BUDGET,
    CATEGORY,
    ITEM,
    ITEM_VARIANT,
    UNIT,
    VENDOR,
    PURCHASE_REQUEST,
    REQUEST_FOR_QUOTATION,
    QUOTATION,
    PURCHASE_ORDER,
    AUDIT_LOGS,
    VIEW_PERMISSION,
    REPEATED_PERIOD
}
